- name: Example playbook
  hosts: localhost
  gather_facts: false
  connection: local
  become: false
  vars:
    env1: "{{ lookup('ansible.builtin.env', 'ENV1', default='') }}"
    endpoint: "{{ lookup('ansible.builtin.env', 'ENDPOINT', default=Undefined) }}" # fails if not set
    access_token: "{{ lookup('ansible.builtin.env', 'ACCESS_TOKEN', default=Undefined) }}" # fails if not set

    template_input:
      A:
        a1: 'a 1'
        a2: 'a 2'
        extra: '123'
      B:
        b1: 'b 1'
        b2: 'b 2'

  module_defaults:
    ansible.builtin.uri:
      ca_path: "{{ lookup('ansible.builtin.env', 'CA_PATH', default='') | default(omit, true) }}"

  pre_tasks:
    - name: Check if ENDPOINT is defined
      ansible.builtin.fail:
        msg:
          - "Missing environment variables"
      when: endpoint is not defined or access_token is not defined
    - name: Set inputs facts
      ansible.builtin.set_fact:
        async_inputs:
          - '1'
          - '2'
          - '3'
    - name: Set inputs facts from template that generates YAML
      ansible.builtin.set_fact:
        variables: "{{ lookup('ansible.builtin.template', 'templates/variables.j2') | ansible.builtin.from_yaml }}"
    - name: Debug
      ansible.builtin.debug:
        var: variables

  roles:
    - role: example
      vars:
        role_example_input: 'example role parameter'
      tags:
        - test1
    # - role: example-async-batch
    #   inputs: "{{ async_inputs }}"
    #   vars:
    #     role_example_async_batch_size: 2

  tasks:

    - name: hostvars
      ansible.builtin.debug:
        var: hostvars[inventory_hostname]
        # verbosity: 1 # only run on -v
      tags:
        - debug

    - name: Output variables
      ansible.builtin.debug:
        var: env1
      tags:
        - debug

    - name: Print variables
      ansible.builtin.include_tasks: tasks/task.yml
      vars:
        param: "{{ item }}"
      loop: 
        - foo
        - bar
        - "{{ endpoint }}"
        - "{{ access_token }}"
        - "{{ env1 | default(omit, True) }}" # default an empty string to an omit-token
        - "{{ username }}"
        - "{{ password }}"
      tags:
        - debug

    - name: Run a task
      ansible.builtin.import_tasks: tasks/json-query.yml
      tags:
        - never
        - test # ansible-playbook --tags test project/playbook.yml
    
    - name: Jinja2 template
      ansible.builtin.template:
        src: templates/note.j2
        dest: /tmp/note

  post_tasks:
    - name: Example post task
      ansible.builtin.debug:
        msg: 'Post task'
